Neos:
  Flow:
    http:
      middlewares:
        'Flownative.GraphQL':
          'position': 'start'
          middleware: 'Flownative\GraphQL\Middleware'

Flownative:
  GraphQL:
    debug:
      includeDebugMessage: true
      includeTrace: true
